---
openapi: 3.0.0
info:
  title: Realty value calculator
  contact: {}
  version: "1.0"
servers:
  - url: http://localhost:8080
tags:
  - name: Realty
    description: ""
paths:
  /realty/objects/import:
    put:
      tags:
        - Realty
      summary: Импорт из XLSX-файла
      description: Импортировать объекты недвижимости из файла
      operationId: ИмпортизXLSX-файла
      parameters:
        - name: userSessionId
          in: header
          description: userSessionId из Cookie
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 21a45861-2308-45f1-93a4-21be5f06ecd7
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/objects_import_body'
            encoding: {}
        required: false
      responses:
        "200":
          description: OK
          headers:
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "0"
          content: {}
        "400":
          description: BadRequest
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: text/plain
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "19"
          content:
            text/plain:
              schema:
                type: string
                example: Invalid file format
              example: Invalid file format
        "401":
          description: Unauthorized
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: text/plain
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "31"
          content:
            text/plain:
              schema:
                type: string
                example: Header userSessionId is not set
              example: Header userSessionId is not set
        "500":
          description: Internal server error
      deprecated: false
  /realty/objects/create:
    post:
      tags:
        - Realty
      summary: Создание объекта недвижимости
      operationId: createrealtyobject
      parameters:
        - name: userSessionId
          in: header
          description: userSessionId Cookie
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 21a45861-2308-45f1-93a4-21be5f06ecd7
      requestBody:
        description: Значения полей создаваемого объекта недвижимости.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/objects_create_body'
            example:
              location: Саринский пр-д, 42, Москва, 127524
              roomsNumber: 3
              segment: Новостройка
              floorCount: 10
              wallMaterial: кирпич
              floorNumber: 4
              totalArea: 75
              kitchenArea: 12
              gotBalcony: true
              condition: Современная отделка
              distanceFromMetro: 200
        required: true
      responses:
        "200":
          description: OK
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: application/json
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "398"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              example:
                id: 0e7ec6a5-59a4-45cf-8528-c33efe8c83dd
                location: Саринский пр-д, 42, Москва, 127524
                roomsNumber: 3
                segment: Новостройка
                floorCount: 10
                wallMaterial: кирпич
                floorNumber: 4
                totalArea: 75
                kitchenArea: 12
                gotBalcony: true
                condition: Современная отделка
                distanceFromMetro: 200
                createdAt: 2022-10-30T02:15:31.4185054
        "400":
          description: Session not found
        "401":
          description: Unauthorized
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: text/plain
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "31"
          content:
            text/plain:
              schema:
                type: string
                example: Header userSessionId is not set
              example: Header userSessionId is not set
        "500":
          description: Internal server error
      deprecated: false
  /realty/objects:
    get:
      tags:
        - Realty
      summary: Получить все объекты недвижимости, созданные авторизованным пользователем
      operationId: getrealtyobjectscreatedbyuser
      parameters:
        - name: userSessionId
          in: header
          description: userSessionId from Cookie
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 21a45861-2308-45f1-93a4-21be5f06ecd7
      responses:
        "200":
          description: OK
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: application/json
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "6529"
          content:
            application/json:
              schema:
                type: array
                description: ""
                example:
                  - id: 8a7395e0-8bfe-4c9f-b322-cd48d519c21c
                    location: Адрес 1
                    roomsNumber: 3
                    segment: Новостройка
                    floorCount: 5
                    wallMaterial: кирпич
                    floorNumber: 3
                    totalArea: 70
                    kitchenArea: 15
                    gotBalcony: false
                    condition: без отделки
                    distanceFromMetro: 500
                    addedByUserId: 90b72302-b5ae-4d00-9067-a061edd5fd33
                    createdAt: 2022-10-30T02:14:13.618054
                    updatedAt: 2022-10-30T02:14:13.618054
                  - id: 5e892bab-7d21-4571-8425-2235d1e0d2f5
                    location: Адрес 2
                    roomsNumber: 2
                    segment: Современное жилье
                    floorCount: 6
                    wallMaterial: панель
                    floorNumber: 5
                    totalArea: 50
                    kitchenArea: 10
                    gotBalcony: true
                    condition: муниципальный ремонт
                    distanceFromMetro: 400
                    addedByUserId: 90b72302-b5ae-4d00-9067-a061edd5fd33
                    createdAt: 2022-10-30T01:48:21.356481
                    updatedAt: 2022-10-30T01:48:21.356481
                  - id: bf070e18-81f6-4520-b892-ec881734367c
                    location: Адрес 3
                    roomsNumber: 1
                    segment: старый жилой фонд
                    floorCount: 7
                    wallMaterial: монолит
                    floorNumber: 7
                    totalArea: 30
                    kitchenArea: 5
                    gotBalcony: true
                    condition: современная отделка
                    distanceFromMetro: 100
                    addedByUserId: 90b72302-b5ae-4d00-9067-a061edd5fd33
                    createdAt: 2022-10-30T01:48:21.362481
                    updatedAt: 2022-10-30T01:48:21.362481
                  - id: 0e7ec6a5-59a4-45cf-8528-c33efe8c83dd
                    location: Саринский пр-д, 42, Москва, 127524
                    roomsNumber: 3
                    segment: Новостройка
                    floorCount: 10
                    wallMaterial: кирпич
                    floorNumber: 4
                    totalArea: 75
                    kitchenArea: 12
                    gotBalcony: true
                    condition: Современная отделка
                    distanceFromMetro: 200
                    addedByUserId: 90b72302-b5ae-4d00-9067-a061edd5fd33
                    createdAt: 2022-10-30T02:15:31.418505
                    updatedAt: 2022-10-30T02:15:31.418505
                items:
                  $ref: '#/components/schemas/getrealtyobjectscreatedbyuser'
              example:
                - id: 8a7395e0-8bfe-4c9f-b322-cd48d519c21c
                  location: Адрес 1
                  roomsNumber: 3
                  segment: Новостройка
                  floorCount: 5
                  wallMaterial: кирпич
                  floorNumber: 3
                  totalArea: 70
                  kitchenArea: 15
                  gotBalcony: false
                  condition: без отделки
                  distanceFromMetro: 500
                  addedByUserId: 90b72302-b5ae-4d00-9067-a061edd5fd33
                  createdAt: 2022-10-30T02:14:13.618054
                  updatedAt: 2022-10-30T02:14:13.618054
                - id: 5e892bab-7d21-4571-8425-2235d1e0d2f5
                  location: Адрес 2
                  roomsNumber: 2
                  segment: Современное жилье
                  floorCount: 6
                  wallMaterial: панель
                  floorNumber: 5
                  totalArea: 50
                  kitchenArea: 10
                  gotBalcony: true
                  condition: муниципальный ремонт
                  distanceFromMetro: 400
                  addedByUserId: 90b72302-b5ae-4d00-9067-a061edd5fd33
                  createdAt: 2022-10-30T01:48:21.356481
                  updatedAt: 2022-10-30T01:48:21.356481
                - id: bf070e18-81f6-4520-b892-ec881734367c
                  location: Адрес 3
                  roomsNumber: 1
                  segment: старый жилой фонд
                  floorCount: 7
                  wallMaterial: монолит
                  floorNumber: 7
                  totalArea: 30
                  kitchenArea: 5
                  gotBalcony: true
                  condition: современная отделка
                  distanceFromMetro: 100
                  addedByUserId: 90b72302-b5ae-4d00-9067-a061edd5fd33
                  createdAt: 2022-10-30T01:48:21.362481
                  updatedAt: 2022-10-30T01:48:21.362481
                - id: 0e7ec6a5-59a4-45cf-8528-c33efe8c83dd
                  location: Саринский пр-д, 42, Москва, 127524
                  roomsNumber: 3
                  segment: Новостройка
                  floorCount: 10
                  wallMaterial: кирпич
                  floorNumber: 4
                  totalArea: 75
                  kitchenArea: 12
                  gotBalcony: true
                  condition: Современная отделка
                  distanceFromMetro: 200
                  addedByUserId: 90b72302-b5ae-4d00-9067-a061edd5fd33
                  createdAt: 2022-10-30T02:15:31.418505
                  updatedAt: 2022-10-30T02:15:31.418505
        "401":
          description: Unauthorized
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: text/plain
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "31"
          content:
            text/plain:
              schema:
                type: string
                example: Header userSessionId is not set
              example: Header userSessionId is not set
      deprecated: false
    patch:
      tags:
        - Realty
      summary: Изменить информацию об объекте недвижимости
      operationId: Updaterealtyobjectinfo
      parameters:
        - name: userSessionId
          in: header
          description: ""
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 21a45861-2308-45f1-93a4-21be5f06ecd7
      requestBody:
        description: Поле id - обязательное поле, представлющее id объекта недвижимости. Остальные поля опциональные, устанавливаются только если нужно обновить значения в них.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/realty_objects_body'
            example:
              id: 8e9f4521-b26c-4529-ab54-524b104d039b
              location: Другой адресc
              roomsNumber: "5"
              segment: Старый жилой фонд
              floorCount: 16
              wallMaterial: монолит
              floorNumber: 9
              totalArea: 74.5
              kitchenArea: 12.3
              gotBalcony: false
              condition: муниципальный ремонт
              distanceFromMetro: 390
              calculatedValue: 18000000
        required: true
      responses:
        "200":
          description: OK
          headers:
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "0"
          content: {}
        "400":
          description: Bad Request
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: text/plain
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "28"
          content:
            text/plain:
              schema:
                type: string
                example: User is not author of object
              example: User is not author of object
        "401":
          description: Unauthorized
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: text/plain
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "31"
          content:
            text/plain:
              schema:
                type: string
                example: Header userSessionId is not set
              example: Header userSessionId is not set
      deprecated: false
  /realty/objects/<RealtyObjectId удаляемого объекта>:
    delete:
      tags:
        - Realty
      summary: Удалить объект недвижимости
      operationId: deleterealtyobject
      parameters:
        - name: userSessionId
          in: header
          description: userSessionId from Cookie
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 21a45861-2308-45f1-93a4-21be5f06ecd7
      responses:
        "200":
          description: OK
          headers:
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "0"
          content: {}
        "401":
          description: Unauthorized
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: text/plain
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "31"
          content:
            text/plain:
              schema:
                type: string
                example: Header userSessionId is not set
              example: Header userSessionId is not set
      deprecated: false
  /realty/objects/<RealtyObjectId извлекаемого объекта>:
    get:
      tags:
        - Realty
      summary: Получить подробную информацию об объекте недвижимости
      operationId: getinfoaboutrealtyobject
      parameters:
        - name: userSessionId
          in: header
          description: userSessionId from Cookie
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 21a45861-2308-45f1-93a4-21be5f06ecd7
      responses:
        "200":
          description: OK
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: application/json
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "409"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
              example:
                id: c3cb4c8a-916d-42de-beab-3b59b0840940
                location: Адрес 1
                roomsNumber: 3
                segment: Новостройка
                floorCount: 5
                wallMaterial: кирпич
                floorNumber: 3
                totalArea: 70
                kitchenArea: 15
                gotBalcony: false
                condition: без отделки
                distanceFromMetro: 500
                calculatedValue: 1000000
                createdAt: 2022-10-30T00:45:14.136715
                updatedAt: 2022-10-30T00:45:14.136715
        "400":
          description: BadRequest
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: text/plain
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "31"
          content:
            text/plain:
              schema:
                type: string
                example: Session not found
              example: Session not found
        "401":
          description: Unauthorized
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: text/plain
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "31"
          content:
            text/plain:
              schema:
                type: string
                example: Header userSessionId is not set
              example: Header userSessionId is not set
      deprecated: false
  /realty/objects/export:
    get:
      tags:
        - Realty
      summary: Экспортировать объекты с рассчитанной стоимостью в xlsx
      operationId: exportrealtyobjectstoxlsx
      parameters:
        - name: userSessionId
          in: header
          description: ""
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 21a45861-2308-45f1-93a4-21be5f06ecd7
      responses:
        "200":
          description: В теле ответа передается xlsx-файл в бинарном формате
          headers:
            content-disposition:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: attachment
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
            transfer-encoding:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: chunked
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                example: binary data here
              example: binary data here
        "401":
          description: Unauthorized
          headers:
            content-type:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: text/plain
            content-length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "31"
          content:
            text/plain:
              schema:
                type: string
                example: Header userSessionId is not set
              example: Header userSessionId is not set
      deprecated: false
  /auth/register:
    post:
      tags:
        - Auth
      summary: Регистрация нового пользователя
      operationId: Registernewuser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_register_body'
            example:
              login: admin
              password: admin
              firstName: Victor
              lastName: Nguen
              birthdate: 09.05.1999
        required: true
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_default'
              example:
                id: cf9934f7-9089-4241-9a1d-0984f13bfcf5
                login: admin
                passwordHash: $2a$10$OrZGbIj4cZvh1Xz2lFrln.w9OApqHiEPd4Ntue0V7VoGW/c9YUB3O
                salt: $2a$10$OrZGbIj4cZvh1Xz2lFrln.
                firstName: Victor
                lastName: Nguen
                birthdate: 1999-05-09
      deprecated: false
  /auth/user:
    post:
      tags:
        - Auth
      summary: Авторизовать пользователя
      operationId: Authorizeuser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_user_body'
            example:
              login: admin
              password: admin
        required: true
      responses:
        default:
          description: ""
          headers:
            set-cookie:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: userSessionId=42aa2a01-ad71-493b-ba99-18bac859f54f
          content: {}
      deprecated: false
  /auth/user/<userId>:
    delete:
      tags:
        - Auth
      summary: Удалить пользователя из системы
      operationId: Deleteuser
      parameters: []
      responses:
        default:
          description: ""
          content: {}
      deprecated: false
      security: []
components:
  schemas:
    createrealtyobjectrequest:
      title: createrealtyobjectrequest
      required:
        - condition
        - distanceFromMetro
        - floorCount
        - floorNumber
        - gotBalcony
        - kitchenArea
        - location
        - roomsNumber
        - segment
        - totalArea
        - wallMaterial
      type: object
      properties:
        location:
          type: string
        roomsNumber:
          type: integer
          format: int32
        segment:
          type: string
        floorCount:
          type: integer
          format: int32
        wallMaterial:
          type: string
        floorNumber:
          type: integer
          format: int32
        totalArea:
          type: integer
          format: int32
        kitchenArea:
          type: integer
          format: int32
        gotBalcony:
          type: boolean
        condition:
          type: string
        distanceFromMetro:
          type: integer
          format: int32
      example:
        location: Саринский пр-д, 42, Москва, 127524
        roomsNumber: 3
        segment: Новостройка
        floorCount: 10
        wallMaterial: кирпич
        floorNumber: 4
        totalArea: 75
        kitchenArea: 12
        gotBalcony: true
        condition: Современная отделка
        distanceFromMetro: 200
    createrealtyobject:
      title: createrealtyobject
      required:
        - condition
        - createdAt
        - distanceFromMetro
        - floorCount
        - floorNumber
        - gotBalcony
        - id
        - kitchenArea
        - location
        - roomsNumber
        - segment
        - totalArea
        - wallMaterial
      type: object
      properties:
        id:
          type: string
        location:
          type: string
        roomsNumber:
          type: integer
          format: int32
        segment:
          type: string
        floorCount:
          type: integer
          format: int32
        wallMaterial:
          type: string
        floorNumber:
          type: integer
          format: int32
        totalArea:
          type: integer
          format: int32
        kitchenArea:
          type: integer
          format: int32
        gotBalcony:
          type: boolean
        condition:
          type: string
        distanceFromMetro:
          type: integer
          format: int32
        createdAt:
          type: string
      example:
        id: 0e7ec6a5-59a4-45cf-8528-c33efe8c83dd
        location: Саринский пр-д, 42, Москва, 127524
        roomsNumber: 3
        segment: Новостройка
        floorCount: 10
        wallMaterial: кирпич
        floorNumber: 4
        totalArea: 75
        kitchenArea: 12
        gotBalcony: true
        condition: Современная отделка
        distanceFromMetro: 200
        createdAt: 2022-10-30T02:15:31.4185054
    getrealtyobjectscreatedbyuser:
      title: getrealtyobjectscreatedbyuser
      required:
        - addedByUserId
        - condition
        - createdAt
        - distanceFromMetro
        - floorCount
        - floorNumber
        - gotBalcony
        - id
        - kitchenArea
        - location
        - roomsNumber
        - segment
        - totalArea
        - updatedAt
        - wallMaterial
      type: object
      properties:
        id:
          type: string
        location:
          type: string
        roomsNumber:
          type: integer
          format: int32
        segment:
          type: string
        floorCount:
          type: integer
          format: int32
        wallMaterial:
          type: string
        floorNumber:
          type: integer
          format: int32
        totalArea:
          type: integer
          format: int32
        kitchenArea:
          type: integer
          format: int32
        gotBalcony:
          type: boolean
        condition:
          type: string
        distanceFromMetro:
          type: integer
          format: int32
        addedByUserId:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 8a7395e0-8bfe-4c9f-b322-cd48d519c21c
        location: Адрес 1
        roomsNumber: 3
        segment: Новостройка
        floorCount: 5
        wallMaterial: кирпич
        floorNumber: 3
        totalArea: 70
        kitchenArea: 15
        gotBalcony: false
        condition: без отделки
        distanceFromMetro: 500
        addedByUserId: 90b72302-b5ae-4d00-9067-a061edd5fd33
        createdAt: 2022-10-30T02:14:13.618054
        updatedAt: 2022-10-30T02:14:13.618054
    userSessionIdisset:
      title: userSessionIdisset
      required:
        - calculatedValue
        - condition
        - createdAt
        - distanceFromMetro
        - floorCount
        - floorNumber
        - gotBalcony
        - id
        - kitchenArea
        - location
        - roomsNumber
        - segment
        - totalArea
        - updatedAt
        - wallMaterial
      type: object
      properties:
        id:
          type: string
        location:
          type: string
        roomsNumber:
          type: integer
          format: int32
        segment:
          type: string
        floorCount:
          type: integer
          format: int32
        wallMaterial:
          type: string
        floorNumber:
          type: integer
          format: int32
        totalArea:
          type: integer
          format: int32
        kitchenArea:
          type: integer
          format: int32
        gotBalcony:
          type: boolean
        condition:
          type: string
        distanceFromMetro:
          type: integer
          format: int32
        calculatedValue:
          type: integer
          format: int32
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: c3cb4c8a-916d-42de-beab-3b59b0840940
        location: Адрес 1
        roomsNumber: 3
        segment: Новостройка
        floorCount: 5
        wallMaterial: кирпич
        floorNumber: 3
        totalArea: 70
        kitchenArea: 15
        gotBalcony: false
        condition: без отделки
        distanceFromMetro: 500
        calculatedValue: 1000000
        createdAt: 2022-10-30T00:45:14.136715
        updatedAt: 2022-10-30T00:45:14.136715
    RegisternewuserRequest:
      title: RegisternewuserRequest
      required:
        - birthdate
        - firstName
        - lastName
        - login
        - password
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        birthdate:
          type: string
      example:
        login: admin
        password: admin
        firstName: Victor
        lastName: Nguen
        birthdate: 09.05.1999
    register:
      title: register
      required:
        - birthdate
        - firstName
        - id
        - lastName
        - login
        - passwordHash
        - salt
      type: object
      properties:
        id:
          type: string
        login:
          type: string
        passwordHash:
          type: string
        salt:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        birthdate:
          type: string
      example:
        id: cf9934f7-9089-4241-9a1d-0984f13bfcf5
        login: admin
        passwordHash: $2a$10$OrZGbIj4cZvh1Xz2lFrln.w9OApqHiEPd4Ntue0V7VoGW/c9YUB3O
        salt: $2a$10$OrZGbIj4cZvh1Xz2lFrln.
        firstName: Victor
        lastName: Nguen
        birthdate: 1999-05-09
    AuthorizeuserRequest:
      title: AuthorizeuserRequest
      required:
        - login
        - password
      type: object
      properties:
        login:
          type: string
        password:
          type: string
      example:
        login: admin
        password: admin
    UpdaterealtyobjectinfoRequest:
      title: UpdatereealtyobjectinfoRequest
      required:
        - calculatedValue
        - condition
        - distanceFromMetro
        - floorCount
        - floorNumber
        - gotBalcony
        - id
        - kitchenArea
        - location
        - roomsNumber
        - segment
        - totalArea
        - wallMaterial
      type: object
      properties:
        id:
          type: string
        location:
          type: string
        roomsNumber:
          type: string
        segment:
          type: string
        floorCount:
          type: integer
          format: int32
        wallMaterial:
          type: string
        floorNumber:
          type: integer
          format: int32
        totalArea:
          type: number
        kitchenArea:
          type: number
        gotBalcony:
          type: boolean
        condition:
          type: string
        distanceFromMetro:
          type: integer
          format: int32
        calculatedValue:
          type: integer
          format: int32
      example:
        id: 8e9f4521-b26c-4529-ab54-524b104d039b
        location: Другой адрес
        roomsNumber: "5"
        segment: Старый жилой фонд
        floorCount: 16
        wallMaterial: монолит
        floorNumber: 9
        totalArea: 74.5
        kitchenArea: 12.3
        gotBalcony: false
        condition: муниципальный ремонт
        distanceFromMetro: 390
        calculatedValue: 18000000
    objects_import_body:
      required:
        - File
      type: object
      properties:
        File:
          type: string
          format: binary
    objects_create_body:
      allOf:
        - $ref: '#/components/schemas/createrealtyobjectrequest'
        - example:
            location: Саринский пр-д, 42, Москва, 127524
            roomsNumber: 3
            segment: Новостройка
            floorCount: 10
            wallMaterial: кирпич
            floorNumber: 4
            totalArea: 75
            kitchenArea: 12
            gotBalcony: true
            condition: Современная отделка
            distanceFromMetro: 200
    inline_response_200:
      allOf:
        - $ref: '#/components/schemas/createrealtyobject'
        - example:
            id: 0e7ec6a5-59a4-45cf-8528-c33efe8c83dd
            location: Саринский пр-д, 42, Москва, 127524
            roomsNumber: 3
            segment: Новостройка
            floorCount: 10
            wallMaterial: кирпич
            floorNumber: 4
            totalArea: 75
            kitchenArea: 12
            gotBalcony: true
            condition: Современная отделка
            distanceFromMetro: 200
            createdAt: 2022-10-30T02:15:31.4185054
    realty_objects_body:
      allOf:
        - $ref: '#/components/schemas/UpdaterealtyobjectinfoRequest'
        - example:
            id: 8e9f4521-b26c-4529-ab54-524b104d039b
            location: Другой адрес
            roomsNumber: "5"
            segment: Старый жилой фонд
            floorCount: 16
            wallMaterial: монолит
            floorNumber: 9
            totalArea: 74.5
            kitchenArea: 12.3
            gotBalcony: false
            condition: муниципальный ремонт
            distanceFromMetro: 390
            calculatedValue: 18000000
    inline_response_200_1:
      allOf:
        - $ref: '#/components/schemas/userSessionIdisset'
        - example:
            id: c3cb4c8a-916d-42de-beab-3b59b0840940
            location: Адрес 1
            roomsNumber: 3
            segment: Новостройка
            floorCount: 5
            wallMaterial: кирпич
            floorNumber: 3
            totalArea: 70
            kitchenArea: 15
            gotBalcony: false
            condition: без отделки
            distanceFromMetro: 500
            calculatedValue: 1000000
            createdAt: 2022-10-30T00:45:14.136715
            updatedAt: 2022-10-30T00:45:14.136715
    auth_register_body:
      allOf:
        - $ref: '#/components/schemas/RegisternewuserRequest'
        - example:
            login: admin
            password: admin
            firstName: Victor
            lastName: Nguen
            birthdate: 09.05.1999
    inline_response_default:
      allOf:
        - $ref: '#/components/schemas/register'
        - example:
            id: cf9934f7-9089-4241-9a1d-0984f13bfcf5
            login: admin
            passwordHash: $2a$10$OrZGbIj4cZvh1Xz2lFrln.w9OApqHiEPd4Ntue0V7VoGW/c9YUB3O
            salt: $2a$10$OrZGbIj4cZvh1Xz2lFrln.
            firstName: Victor
            lastName: Nguen
            birthdate: 1999-05-09
    auth_user_body:
      allOf:
        - $ref: '#/components/schemas/AuthorizeuserRequest'
        - example:
            login: admin
            password: admin
